# Generated by Django 3.1 on 2020-08-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_following_notification_saved_filter_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='crypto_asset',
            new_name='crypto_name',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='crypto_ticker',
            new_name='crypto_symbol',
        ),
    ]
