# Generated by Django 3.1 on 2020-08-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('member', '0005_auto_20200827_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='fifth_argument',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='first_argument',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='fourth_argument',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='second_argument',
        ),
        migrations.RemoveField(
            model_name='saved_filter_group',
            name='third_argument',
        ),
        migrations.CreateModel(
            name='Filter_group_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_argument', models.IntegerField(blank=True, null=True)),
                ('second_argument', models.IntegerField(blank=True, null=True)),
                ('third_argument', models.IntegerField(blank=True, null=True)),
                ('fourth_argument', models.IntegerField(blank=True, null=True)),
                ('fifth_argument', models.IntegerField(blank=True, null=True)),
                ('filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filter.filter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.saved_filter_group')),
            ],
        ),
    ]
