# Generated by Django 3.1 on 2020-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200827_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_group_detail',
            name='fifth_argument',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter_group_detail',
            name='first_argument',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter_group_detail',
            name='fourth_argument',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter_group_detail',
            name='second_argument',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter_group_detail',
            name='third_argument',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
