# Generated by Django 3.1 on 2020-08-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('member', '0007_auto_20200827_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_group_detail',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.filter'),
        ),
    ]
