# Generated by Django 3.1 on 2020-09-08 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20200908_2329'),
        ('member', '0009_auto_20200907_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='crypto_name',
        ),
        migrations.AddField(
            model_name='following',
            name='crypto_id',
            field=models.CharField(default='bitcoin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.CharField(default='mute', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='fifth_argument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='filters',
            field=models.ManyToManyField(related_name='saved_filter_group_filter', to='filter.Filter'),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='first_argument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='fourth_argument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='second_argument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='state',
            field=models.CharField(default='mute', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='third_argument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved_filter_group',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='crypto_symbol',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Filter_group_detail',
        ),
    ]
