# Generated by Django 3.1 on 2020-09-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20200908_2329'),
        ('member', '0010_auto_20200908_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('first_argument', models.BigIntegerField(blank=True, null=True)),
                ('second_argument', models.BigIntegerField(blank=True, null=True)),
                ('third_argument', models.BigIntegerField(blank=True, null=True)),
                ('fourth_argument', models.BigIntegerField(blank=True, null=True)),
                ('fifth_argument', models.BigIntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.filter')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Saved_filter_group',
        ),
        migrations.AddField(
            model_name='filterdetail',
            name='filter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.savedfiltergroup'),
        ),
    ]
