# Generated by Django 3.1 on 2020-09-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20200909_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterdetail',
            name='fifth_argument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterdetail',
            name='first_argument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterdetail',
            name='fourth_argument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterdetail',
            name='second_argument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterdetail',
            name='third_argument',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
