# Generated by Django 3.1 on 2020-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Standard', 'Standard'), ('Liquidity', 'Liquidity'), ('Marketcap', 'Market Cap'), ('Volume', 'Volume'), ('Supply', 'Supply'), ('ROI', 'ROI')], max_length=50)),
                ('filter_content', models.CharField(max_length=200)),
                ('formula_id', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
