# Generated by Django 3.1 on 2020-09-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20200908_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_to_api_field',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
